# Generated by Django 4.2.9 on 2024-03-04 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('bank', 'ifsc_code')},
        ),
    ]
