# Generated by Django 4.2.9 on 2024-03-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newbank', '0002_alter_branch_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='bank_code',
        ),
    ]
