# Generated by Django 4.2.9 on 2024-03-04 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newbank', '0003_remove_branch_bank_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bank_user',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
