# Generated by Django 4.2.9 on 2024-03-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbank', '0004_bank_bank_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='password',
            field=models.CharField(default=21, max_length=12),
            preserve_default=False,
        ),
    ]
