# Generated by Django 4.2.9 on 2024-03-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbank', '0005_bank_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='password',
            field=models.CharField(editable=False, max_length=12),
        ),
    ]
