# Generated by Django 4.2.10 on 2024-03-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newbank', '0011_transaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='managers_ssn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newbank.bankemployee', to_field='employee_number'),
        ),
    ]
